# -*- coding: utf-8 -*-
"""Hard Voting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16P0Z8OzQJGpunnZbd4KDy3cHZkRp7mHN
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import os

def mode(list):
    count = 0
    mode = 0;
    for x in list: 
        if list.count(x) > count:
            count = list.count(x)
            mode = x

    return mode

import os
xlsx_list = [file for file in os.listdir('/content') if file.endswith('csv')]
xlsx_list



num = [i.split('#')[0] for i in xlsx_list]
num = '_'.join(num)
num

y_predict = []
for csv_file in xlsx_list:
  y_predict.append(pd.read_csv(f'/content/{csv_file}').N_category.values)

prediction = []

for i in range(250):
  predict = []
  for j in y_predict:
    predict.append(j[i])
  prediction.append(mode(predict))

submit = pd.read_csv('/content/drive/MyDrive/sample_submission_cancer_cls.csv')

submit['N_category'] = prediction
submit.to_csv(f'./hardvoting_submi.csv', index=False)

submit

from google.colab import files

files.download(f'./hardvoting_submi.csv')